---
- hosts: localhost
  vars:
    quay_config_pass: quayconfig
    # Obtain quay v2 config.json secret from https://access.redhat.com/solutions/3533201
    quayio_config: quay-v3-config.json
  gather_facts: no
  connection: local
  #remote_user: root
  become: yes
  tasks:
  #- name: Register system with activationkey
  #  redhat_subscription:
  #    state: present
  #    activationkey: keyname
  #    org_id: orgname

  # - name: upgrade all packages
  #   yum:
  #     name: '*'
  #     state: latest

  # - name: firewalld configuration
  #   firewalld:
  #     zone: public
  #     port: "{{ item }}"
  #     permanent: yes
  #     state: enable
  #   notify: reload firewalld
  #   loop:
      # - 8443/tcp
      # - 80/tcp 
      # - 443/tcp 
      # - 3306/tcp
      # - 6379/tcp

  - name: add port 80 to firewall trusted zone
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "{{ item }}"
      jump: ACCEPT
      action: insert
    loop:
      - 8443
      - 80 
      - 443 
      - 3306
      - 6379


  - name: create directories for Quay registry container
    file:
      path: "{{ item }}"
      state: directory
      mode: 0777
    with_items:
      - /opt/quay/mysql
      - /opt/quay/redis
      - /opt/quay/config
      - /opt/quay/storage

  - name: copy {{ quayio_config }} into /opt/quay
    copy: src={{ item }} dest=/opt/quay/
    with_items:
      - "{{ quayio_config }}"

  - name: copy systemd podman services into systemd
    copy: src=./systemd/{{ item }} dest=/etc/systemd/system/
    with_items:
      - quay-mysql.service 
      - quay-redis.service 
      - quay-registry.service

  - name: force systemd reload to reread configs
    systemd:
      daemon_reload: yes

  - name: start and enable Quay dependencies (mysql and redis)
    systemd:
      state: started
      name: "{{ item }}"  
      enabled: yes
    with_items:
      - quay-mysql.service 
      - quay-redis.service 

  - name: pulling quay image (This step takes time because it is a huge image)
    shell: |
      echo "Pulling Quay container image"
      podman pull --authfile {{ quayio_config }} \
      quay.io/redhat/quay:v3.2.1

  - name: run quay registry in config mode -- using password {{ quay_config_pass }}
    shell: |
      podman run -d --restart=always \
      --authfile {{ quayio_config }} \
      --name quay-config -p 8443:8443 \
      quay.io/redhat/quay:v3.2.1 config {{ quay_config_pass }}

#####################################################################
# END OF FILE
#####################################################################