---
- hosts: localhost
  gather_facts: no
  connection: local
  #remote_user: root
  become: yes
  tasks:

  - name: extract "quay-config.tar.gz" into /opt/quay/config
    # Extract files into config folder: config.yaml ssl.cert ssl.key
    unarchive:
      src: quay-config.tar.gz
      dest: /opt/quay/config/

  - name: start and enable Quay registry
    systemd:
      state: started
      name: "{{ item }}"  
      enabled: yes
    with_items:
      - quay-redis.service
      - quay-mysql.service
      - quay-registry.service 

#####################################################################
# END OF FILE
#####################################################################